//! Dynamic theme registry: loads built-in JSON themes and user themes.
//!
//! Built-in themes are embedded at compile time via `include_str!`. User
//! themes are loaded from `~/.config/bludio/themes/` at first access.

use std::collections::HashMap;
use std::sync::Arc;
use std::sync::LazyLock;

use super::loader::load_theme_from_json;
use super::types::{Appearance, Theme};

// ── Built-in theme file paths ──────────────────────────────────────────────
// Generated by build.rs from `assets/themes/light/` and `assets/themes/dark/`.

include!(concat!(env!("OUT_DIR"), "/builtin_themes.rs"));

// ── ThemeRegistry ──────────────────────────────────────────────────────────

/// Dynamic theme registry holding all loaded themes.
struct ThemeRegistry {
    themes: HashMap<String, Arc<Theme>>,
    light_ids: Vec<String>,
    dark_ids: Vec<String>,
}

impl ThemeRegistry {
    fn new() -> Self {
        let mut themes = HashMap::new();
        let mut light_ids = Vec::new();
        let mut dark_ids = Vec::new();

        // Load built-in light themes
        for (id, content) in BUILTIN_LIGHT {
            match load_theme_from_json(content, Appearance::Light) {
                Ok(theme) => {
                    light_ids.push(theme.id.clone());
                    themes.insert(theme.id.clone(), Arc::new(theme));
                }
                Err(e) => {
                    eprintln!("[theme-registry] Failed to load built-in light theme {id}: {e}")
                }
            }
        }

        // Load built-in dark themes
        for (id, content) in BUILTIN_DARK {
            match load_theme_from_json(content, Appearance::Dark) {
                Ok(theme) => {
                    dark_ids.push(theme.id.clone());
                    themes.insert(theme.id.clone(), Arc::new(theme));
                }
                Err(e) => {
                    eprintln!("[theme-registry] Failed to load built-in dark theme {id}: {e}")
                }
            }
        }

        // Load user themes
        Self::load_user_themes(&mut themes, &mut light_ids, &mut dark_ids);

        Self {
            themes,
            light_ids,
            dark_ids,
        }
    }

    /// Scan user theme directories and load valid themes.
    /// User themes override built-in themes with the same ID.
    fn load_user_themes(
        themes: &mut HashMap<String, Arc<Theme>>,
        light_ids: &mut Vec<String>,
        dark_ids: &mut Vec<String>,
    ) {
        let base_dir = user_themes_dir();
        let light_dir = base_dir.join("light");
        let dark_dir = base_dir.join("dark");

        Self::load_dir(&light_dir, Appearance::Light, themes, light_ids);
        Self::load_dir(&dark_dir, Appearance::Dark, themes, dark_ids);
    }

    fn load_dir(
        dir: &std::path::Path,
        appearance: Appearance,
        themes: &mut HashMap<String, Arc<Theme>>,
        ids: &mut Vec<String>,
    ) {
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(_) => return, // Directory doesn't exist — that's fine
        };

        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }

            let content = match std::fs::read_to_string(&path) {
                Ok(c) => c,
                Err(e) => {
                    eprintln!("[theme-registry] Failed to read {}: {e}", path.display());
                    continue;
                }
            };

            match load_theme_from_json(&content, appearance) {
                Ok(theme) => {
                    let id = theme.id.clone();
                    // Remove old ID if overriding (built-in or previous user theme)
                    ids.retain(|existing| existing != &id);
                    ids.push(id.clone());
                    themes.insert(id, Arc::new(theme));
                }
                Err(e) => {
                    eprintln!("[theme-registry] Failed to load {}: {e}", path.display());
                }
            }
        }
    }
}

// ── LazyLock singleton ─────────────────────────────────────────────────────

static REGISTRY: LazyLock<ThemeRegistry> = LazyLock::new(ThemeRegistry::new);

// ── Public helpers ─────────────────────────────────────────────────────────

/// Look up a theme by its stable string ID.
/// Returns `None` if the ID is not known.
pub(crate) fn theme_for_id(id: &str) -> Option<Arc<Theme>> {
    REGISTRY.themes.get(id).cloned()
}

/// Return the display name for a theme ID.
pub(crate) fn theme_display_name(id: &str) -> Option<&str> {
    REGISTRY.themes.get(id).map(|t| t.display_name.as_str())
}

/// All registered light theme IDs.
pub(crate) fn light_theme_ids() -> Vec<&'static str> {
    // Leak the strings to get 'static references — the registry lives forever.
    REGISTRY
        .light_ids
        .iter()
        .map(|s| {
            let leaked: &'static str = Box::leak(s.clone().into_boxed_str());
            leaked
        })
        .collect()
}

/// All registered dark theme IDs.
pub(crate) fn dark_theme_ids() -> Vec<&'static str> {
    REGISTRY
        .dark_ids
        .iter()
        .map(|s| {
            let leaked: &'static str = Box::leak(s.clone().into_boxed_str());
            leaked
        })
        .collect()
}

// ── Config path helpers ────────────────────────────────────────────────────

fn user_themes_dir() -> std::path::PathBuf {
    std::env::var("XDG_CONFIG_HOME")
        .map(std::path::PathBuf::from)
        .or_else(|_| {
            std::env::var("HOME").map(|home| {
                std::path::PathBuf::from(home)
                    .join(".config")
                    .join("bludio")
                    .join("themes")
            })
        })
        .unwrap_or_else(|_| {
            std::path::PathBuf::from("/tmp")
                .join("bludio")
                .join("themes")
        })
}
